# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.10.1
    working_directory: /go/src/github.com/dennisstritzke/ipsec_exporter
    steps:
      - checkout
      - run: go get github.com/Masterminds/glide
      - run: glide install
      - run: go test -v $(glide novendor)
      - save_cache:
          key: golang-ipsec_exporter-vendor
          paths:
            - "vendor"
  build:
    docker:
      - image: circleci/golang:1.10.1
    working_directory: /go/src/github.com/dennisstritzke/ipsec_exporter
    steps:
      - checkout
      - restore_cache:
          keys:
            - golang-ipsec_exporter-vendor
      - run:
          name: Build Golang binary
          command: go build -a -installsuffix cgo -o binaries/ipsec_exporter github.com/dennisstritzke/ipsec_exporter
          environment:
            GOOS: linux
            GOARCH: amd64
            CGO_ENABLED: 0
      - persist_to_workspace:
          root: "binaries"
          paths:
            - "*"
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/binaries
      - run:
          name: Prepare release artifacts
          command: |
            mv /tmp/binaries/ipsec_exporter /tmp/binaries/ipsec_exporter-${CIRCLE_TAG}.linux-amd64
            mkdir -p /tmp/artifacts
            tar czvf /tmp/artifacts/ipsec_exporter-${CIRCLE_TAG}.linux-amd64.tar.gz -C /tmp/binaries ipsec_exporter-${CIRCLE_TAG}.linux-amd64
            cd /tmp/artifacts
            sha256sum * > sha256sums.txt
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} /tmp/artifacts/

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/